/* eslint-disable @typescript-eslint/no-require-imports -- Standalone regression checks. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const ts = require('typescript');
const source = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
const dto = {};
vm.runInNewContext(ts.transpileModule(source('lib/api/dto.ts'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText, {exports:dto,require,URL});
assert.equal(dto.weatherResponseSchema.safeParse({forecastAt:'2026-09-08T12:15:00+09:00',temperatureC:23.2,precipitationProbability:70,sky:'overcast',precipitationType:'rain',source:'open_meteo'}).success,true);
assert.equal(dto.weatherResponseSchema.safeParse({forecastAt:'2026-09-08T12:15:00',temperatureC:null,precipitationProbability:null,sky:null,precipitationType:null}).success,true);
const header = source('components/AppHeader.tsx');
assert.ok(header.includes('aria-controls="mobile-navigation"'));
assert.ok(header.includes('aria-expanded={menuOpen}'));
assert.ok(header.includes('모바일 메뉴'));
assert.ok(header.includes('로그인·회원가입'));
const footer = source('components/SiteFooter.tsx');
assert.ok(!footer.includes('033-000-0000'));
assert.ok(!footer.includes('sports@gangwon.go.kr'));
assert.ok(footer.includes('/terms/privacy'));
const password = source('components/PasswordChangePage.tsx');
assert.ok(password.includes('formElement.reset()'));
assert.ok(!password.includes('event.currentTarget.reset()'));
const home = source('components/HomePage.tsx');
assert.ok(home.includes('자동 넘김 멈춤'));
assert.ok(home.includes('prefers-reduced-motion'));
assert.ok(home.includes('날씨 다시 불러오기'));
assert.ok(!home.includes('eventImage1'));
const community = source('components/CommunityPage.tsx');
assert.ok(community.includes('postLocks.current.has'));
assert.ok(community.includes('href={loginUrl}'));
assert.ok(community.includes('key={params.toString()}'));
const saved = source('components/SaveActivityButton.tsx');
assert.ok(saved.includes('key={activityId}'));
assert.ok(saved.includes('저장 상태를 변경하지 못했습니다'));
console.log('PASS: final polish weather contract, mobile auth, honest footer, safe async forms, photo feed');
