import {
  Activity,
  ArrowRight,
  Award,
  BadgeCheck,
  Bookmark,
  CalendarDays,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  CloudSun,
  Dumbbell,
  Flame,
  Gift,
  Handshake,
  Heart,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Mountain,
  Newspaper,
  PersonStanding,
  Phone,
  Search,
  Smile,
  Snowflake,
  Trophy,
  Timer,
  Users,
  Waves,
  Zap,
  type LucideProps,
} from "lucide-react";

const icons = {
  activity: Activity,
  arrowRight: ArrowRight,
  award: Award,
  badgeCheck: BadgeCheck,
  bookmark: Bookmark,
  calendar: CalendarDays,
  checkCircle: CheckCircle2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboard: ClipboardList,
  cloudSun: CloudSun,
  dumbbell: Dumbbell,
  flame: Flame,
  gift: Gift,
  handshake: Handshake,
  heart: Heart,
  lock: Lock,
  mail: Mail,
  map: Map,
  mapPin: MapPin,
  medal: Medal,
  mountain: Mountain,
  newspaper: Newspaper,
  person: PersonStanding,
  phone: Phone,
  search: Search,
  smile: Smile,
  snowflake: Snowflake,
  trophy: Trophy,
  timer: Timer,
  users: Users,
  waves: Waves,
  zap: Zap,
} as const;

export type AppIconName = keyof typeof icons;

export function AppIcon({ name, className = "size-[1em]", ...props }: LucideProps & { name: AppIconName }) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" focusable="false" className={`inline-block shrink-0 ${className}`} {...props} />;
}
